name: Auto Merge Develop to Main

on:
  push:
    branches:
      - develop # Substitua pelo branch que o Jules faz push

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git user
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Fetch all branches
        run: git fetch --all

      - name: Merge develop into main
        run: |
          git checkout main
          git merge origin/develop --no-ff -m "Auto-merge develop into main"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
